B.pyを作りました #1
furu1124date/gitremote2 pull request #6
Opened 2024-10-31 03:33 UTC by maca-11

レビューお願いします

2024-10-31 03:35 UTC, iina1003 approved these changes
okかも～

2024-10-31 03:35 UTC, furu1124date commented on B.py
> +def hallo():
違うなぁ

2024-10-31 03:40 UTC, furu1124date requested changes

2024-10-31 03:40 UTC, furu1124date commented on B.py
> +def hallo():
bbbbbbbbbbbaaaaaaaaaaaaaakkkkkkkkkkkkkkkaaaaaaaaaaaa
```suggestion
def hello():
```

2024-11-01 02:19 UTC, iina1003 commented on B.py
> +def hallo():
ごめん俺の目は節穴や

2024-11-01 02:24 UTC, furu1124date approved these changes
おkだからね～

2024-11-01 02:27 UTC, closed without merging